### ISSUE TITLE
[Refactor] todolist 페이지 코드 리팩토링, 오류 수정

### ISSUE THREAD

**Issue by hb9901** [B03-Killer/WorkConnect#118]
## Description
todolist 페이지 코드 리팩토링, 오류 수정

## To-Do
- [x] todolist 페이지 코드 리팩토링
- [x] todolist 페이지 오류 수정
- [x] 메인 페이지 프로필 선택 시 정보 표시 오류 수정

## up-to-date
2024.08.02
