### ISSUE TITLE
[feat] 채팅 버그 수정

### ISSUE THREAD

**Issue by 1eeyerin** [B03-Killer/WorkConnect#119]
## To-Do
- [x] fix: 채팅 리렌더링 이슈 수정
- [x] fix: 채팅 화면 바깥을 클릭하면 유틸 메뉴가 닫힌다
- [x] feat: 대화창 이름 수정
