### ISSUE TITLE
[fix] 메인페이지, todolist 페이지, 프로필 편집 페이지 기능 수정

### ISSUE THREAD

**Issue by hb9901** [B03-Killer/WorkConnect#136]
## Description
메인페이지, todolist 페이지, 프로필 편집 페이지 기능 수정

## To-Do
- [x] 메인 페이지 헤더 수정
- [x] 메인 페이지, todolist bottomsheet 위치 변경
- [x] 메인 페이지 사람 없는지 확인하는 로직 수정
- [x] 프로필 페이지 메시지 보내기 기능 수정
- [x] 프로필 페이지 수정 페이지 글자 없을 시 시스템 컴포넌트 간격 수정
- [x] 프로필 페이지 바텀 시트 입력값 상태 관리
- [x] todolist 버튼 변경

## up-to-date
2024.08.02
