### ISSUE TITLE
[feat] 공지 등록시 리얼타임 반영

### ISSUE THREAD

**Issue by 1eeyerin** [B03-Killer/WorkConnect#172]
## To-Do
- [x] feat: 공지 등록시 리얼타임 반영
- [x] style: 채팅 텍스트 선택시 스타일 제거
- [x] fix: 메뉴에서 상세 이동시 replace 로직을 하여 history를 쌓지 않는다
