### ISSUE TITLE
style: 체크 아이콘 변경

### ISSUE THREAD

**Issue by 1eeyerin** [B03-Killer/WorkConnect#174]
## To-Do
- [x] feat: 메인 페이지에서 나를 클릭하면 내 프로필 페이지로 이동한다.
- [x] style: 스크롤바 숨기기
- [x] style: 체크 아이콘 변경
