### ISSUE TITLE
[feat] 유저 정보와 화상채팅방 정보 연동

### ISSUE THREAD

**Issue by MinKonKim** [B03-Killer/WorkConnect#22]
## To-Do
- [ ] 유저 정보 작성
- [ ] 유저 선택 기능 구현
- [ ] 채널에 있는 유저 정보 저장
- [ ] 초대받은 채널과 , 초대한 채널 구분
