### ISSUE TITLE
[refactor] 채팅 목록 페이지 리팩터링

### ISSUE THREAD

**Issue by 1eeyerin** [B03-Killer/WorkConnect#229]
## To-Do
- [ ] 채팅 목록페이지 리팩터링 (리렌더링 최소화, 코드 가독성 향상, 관심사 분리)
- [ ] 채팅 infinite scroll 구현
- [ ] 채팅 목록 로직 공통 컴포넌트로 리팩터링
- [ ] 채널 이름 api 호출 개선
