### ISSUE TITLE
[style] 홈 페이지 및 헤더 반응형 디자인 적용

### ISSUE THREAD

**Issue by hb9901** [B03-Killer/WorkConnect#236]
## Description
무슨 스타일을 작업중인지 작성해주세요.홈 페이지 및 헤더 반응형 디자인 적용

## To-Do
- [x] 멤버가 존재 할 시 홈페이지 반응형 스타일 적용
- [x] 멤버가 없을 시 홈페이지 반응형 스타일 적용
- [x] 헤더 반응형 스타일 

## up-to-date
2024.08.08
