### ISSUE TITLE
[style] 포커싱 되는 화면  UI 수정.

### ISSUE THREAD

**Issue by MinKonKim** [B03-Killer/WorkConnect#271]
## To-Do
- [ ] layout 수정 (미정
- [ ] 포커싱 기준 수정
- [ ] 화면 출력시 , 네임 태그 설정.
