### ISSUE TITLE
[fix] 프로필 페이지 예외처리, todo 수정 페이지 모달 수정

### ISSUE THREAD

**Issue by hb9901** [B03-Killer/WorkConnect#276]
## Description
프로필 페이지 예외처리, todo 수정 페이지 모달 수정

## To-Do
- [x] 프로필 페이지 띄운 상태에서 헤더에서 워크 스페이스 이동시 에러
- [x] input 없을 때 예외처리 
- [x] input 최대 길이 설정
- [x] todo 수정 페이지 모달 수정
- [x] todolist 메인 페이지 요일 띄우기

## up-to-date
2024.08.14
