### ISSUE TITLE
[feat] 공지방 생성시 채널 목록에 노출되도록 개선

### ISSUE THREAD

**Issue by 1eeyerin** [B03-Killer/WorkConnect#312]
## Description
- 채팅 sql 쿼리 수정
  - 1명이 참가하는 방도 노출되도록 쿼리 개선
  -  is_dm 조건문 수정
  - chat realtime handler 실행시 나의 채팅방 접속시간 db 업데이트
  - channel_thumbnail 로직 수정

## To-Do
- [x] style: pc bottom bar 상단까지 채움
- [x] style: 모바일일때 채팅방 넘치는 오류 수정
- [x] refactor: dm 방이면 채널 이름이 없다, 채널 이름이 비어있으면 유저 이름이 보이게 변경
- [x] feat: realtime 에서 chat 업데이트가 생기면 채팅방 접속 시간을 db에 업데이트
- [x] refactor: 채널 목록 rpc name 수정, channel_name 통일
- [x] refactor: user_thumbnail과 channel_thumbnail 모두 내려오게 한다
