### ISSUE TITLE
[feat] 채팅 1차 개발 구현

### ISSUE THREAD

**Issue by 1eeyerin** [B03-Killer/WorkConnect#32]
## To-Do
- [x] 채널 목록 구현
- [x] 채널 상세 구현
- [x] 채널 추가 구현
