### ISSUE TITLE
[feat] 컨벤션 관리 자동화 : Git Hooks를 이용한 커밋메세지 및 Lint 관리

### ISSUE THREAD

**Issue by 1eeyerin** [B03-Killer/WorkConnect#375]
## To-Do
- [ ] 커밋메세지 규격화 (대소문자 구분 및 한국어 메세지 강제화 시킬수는 없는지?)
- [ ] 브랜치 이름 규격화 (feature/#티켓번호를 강제화 시킬수는 없는지?)
- [x] Lint 오류시 push 에러 발생
- [x] npm package update
- [x] eslint 관련 패키지 설치
- [x] import React 과거 호환성 관련 에러 무시 처리  (eslint)
- [x] .eslintcache gitignore
- [x] babel presets 추가 설정
