### ISSUE TITLE
[refactor] 채팅 리팩터링

### ISSUE THREAD

**Issue by 1eeyerin** [B03-Killer/WorkConnect#395]
## Description
- [fix] realtime postgres delete 이벤트 오류 수정
  - https://supabase.com/docs/guides/realtime/postgres-changes#delete-events-are-not-filterable

- [refactor] chat.tsx 조건부 렌더링 간소화
- [refactor] 예외처리와 로깅 처리
- [refactor] middleware 로직 분리, 쿠키 업데이트 로직 분리

## To-Do
- [x] [refactor] chat.tsx 조건부 렌더링 간소화
- [x] [refactor] 예외처리와 로깅 처리
- [x] [refactor] middleware 로직 분리, 쿠키 업데이트 로직 분리
