### ISSUE TITLE
[refactor] supabase scheduler workflow 추가

### ISSUE THREAD

**Issue by 1eeyerin** [B03-Killer/WorkConnect#399]
## To-Do
- [x] supabase scheduler workflows 추가
- [x] nvmrc 추가
- [x] 프로젝트 지원 범위 추가
- [x] svgr 설정 수정
